csm:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: cstery_mall_db
    username: root
    password: 1151259363
  jwt:
    admin-secret-key: cstery
    admin-ttl: 7200000
    admin-token-name: token

    user-secret-key: fjcstery
    user-ttl: 7200000
    user-token-name:



