server:
  port: 8083
spring:
  web:
    resources:
      static-locations: classpath:/static
  servlet:
    multipart:
      max-request-size: ${csm.servlet.multipart.max-request-size}
      max-file-size: ${csm.servlet.multipart.max-file-size}


csm:
  jwt:
    admin-secret-key: ${csm.jwt.admin-secret-key} #设置jwt签名加密时使用的密钥
    admin-ttl: ${csm.jwt.admin-ttl} #设置jwt过期的时间
    admin-token-name: ${csm.jwt.admin-token-name} #设置前端传递过来的令牌名称
    user-secret-key: ${csm.jwt.user-secret-key}
    user-ttl: ${csm.jwt.user-ttl}
    user-token-name: ${csm.jwt.user-token-name}
  alioss:
    endpoint: ${csm.alioss.endpoint}
    bucket-name: ${csm.alioss.bucket-name}
    access-key-secret: ${csm.alioss.access-key-secret}
    access-key-id: ${csm.alioss.access-key-id}