csm:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.88.156
    port: 3306
    database: csm-user
    username: root
    password: 1151259363
  jwt:
    admin-secret-key: cstery
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: fjcstery
    user-ttl: 7200000
    user-token-name: authorization
  swagger:
    title: 'cstery-mall用户相关接口文档'
    desc: 'cstery-mall用户相关接口文档'
    admin-group-name: '管理端用户相关接口文档'
    admin-package: com.cstery.user.controller.admin
    user-group-name: '用户端用户接口文档'
    user-package: com.cstery.user.controller.user
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 20MB   # 设置上传文件大小，默认是1M
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: cstery-sky
    access-key-secret: zZhUThCwH54quUEKL8l2UvBtavsj6W
    access-key-id: LTAI5tMLyK8pQCwzKqqnPoyk

