server:
  port: 8084
spring:
  web:
    resources:
      static-locations: classpath:/static/images
  servlet:
    multipart:
      max-request-size: ${csm.servlet.multipart.max-request-size}
      max-file-size: ${csm.servlet.multipart.max-file-size}
feign:
  okhttp:
    enabled: true
csm:
  alioss:
    endpoint: ${csm.alioss.endpoint}
    bucket-name: ${csm.alioss.bucket-name}
    access-key-secret: ${csm.alioss.access-key-secret}
    access-key-id: ${csm.alioss.access-key-id}