csm:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.88.156
    port: 3306
    database: csm-product
    username: root
    password: 1151259363
    package: com.cstery.product.domain.po
  swagger:
    title: 'cstery-mall商品相关接口文档'
    desc: 'cstery-mall商品相关接口文档'
    admin-group-name: '管理端商品相关接口文档'
    admin-package: com.cstery.product.controller.admin
    user-group-name: '用户端商品接口文档'
    user-package: com.cstery.product.controller.user
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 20MB   # 设置上传文件大小，默认是1M
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: cstery-sky
    access-key-secret: zZhUThCwH54quUEKL8l2UvBtavsj6W
    access-key-id: LTAI5tMLyK8pQCwzKqqnPoyk
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 7

